# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
author: Nazmul Idris
title: developerlife.com
description: >- # this means to ignore newlines until "baseurl:"
  Hi, I'm Nazmul Idris. I am a Googler, entrepreneur, leader, coder, designer, dancer, TaiChi’er,
  Yogi, racer, healer, storyteller. I’m about leadership, authenticity, and empowerment.

  I started this website in Nov 1998 when I couldn’t find a decent tutorial on XML and Java
  to build web based apps, so I decided to write one myself, and this site was born. Today I cover
  Android, Web, Cloud technologies, and UX engineering and design topics.

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: "https://nazmulidris.github.io"

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: "/developerlife.com"

linkedin_username: nazmulidris
github_username: nazmulidris
youtube_username: nazmulidris
googleplus_username: +NazmulIdris
google_analytics: UA-3038460-3
medium_username: nazmul

#
# Build settings
#
markdown: kramdown
highlighter: rouge
theme: minima
plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed

# Allow Github Flavored Markdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Show excerpts on the homepage
show_excerpts: true

# Exclude these files from your production _site
exclude:
- Gemfile
- Gemfile.lock
- LICENSE
- README.md
- CNAME
