# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server
# process.

# Site settings.
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
author: Nazmul Idris
title: developerlife.com
email: idris@developerlife.com
description: >- # this means to ignore newlines until "url:"
  Android, Web, Desktop, Cloud technologies, and UX engineering and design tutorials.

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: "http://developerlife.com"

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name".
baseurl: ""

google_analytics: G-NQY9ECC58H

# Build settings.
markdown: kramdown
highlighter: rouge
theme: minima
plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed

# Allow Github Flavored Markdown.
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Show excerpts on the homepage.
show_excerpts: true

# Exclude these files from your production _site.
exclude:
- Gemfile
- Gemfile.lock
- LICENSE
- README.md
- CNAME

# Disable RSS feed.
show_rss_feed: true

# Set permalink style to match Wordpress.com.
permalink: :year/:month/:day/:slug/

# Collections for author pages support.
# More info: https://jekyllrb.com/docs/step-by-step/09-collections/
collections:
  authors:
    output: true